//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyMealPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMeal
    {
        public long DailyMealID { get; set; }
        public long BreakfastID { get; set; }
        public long LunchID { get; set; }
        public long DinnerID { get; set; }
        public long SnackID { get; set; }
        public long TotalCals { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> Snack2ID { get; set; }
        public Nullable<long> Snack3ID { get; set; }
        public Nullable<long> Snack4ID { get; set; }
        public Nullable<long> Snack5ID { get; set; }
        public Nullable<long> Snack6ID { get; set; }
    
        public virtual Breakfast Breakfast { get; set; }
        public virtual Dinner Dinner { get; set; }
        public virtual Lunch Lunch { get; set; }
        public virtual Snack Snack { get; set; }
        public virtual Snack Snack1 { get; set; }
        public virtual Snack Snack2 { get; set; }
        public virtual Snack Snack3 { get; set; }
        public virtual Snack Snack4 { get; set; }
        public virtual Snack Snack5 { get; set; }
        public virtual Snack Snack6 { get; set; }
    }
}
