//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyMealPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dinner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dinner()
        {
            this.DailyMeals = new ObservableListSource<DailyMeal>();
        }
    
        public long DinnerID { get; set; }
        public Nullable<long> Calories { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals { get; set; }
    }
}
