//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyMealPlan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DailyMealsEntities : DbContext
    {
        public DailyMealsEntities()
            : base("name=DailyMealsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breakfast> Breakfasts { get; set; }
        public virtual DbSet<BreakfastItem> BreakfastItems { get; set; }
        public virtual DbSet<DailyMeal> DailyMeals { get; set; }
        public virtual DbSet<Dinner> Dinners { get; set; }
        public virtual DbSet<DinnerItem> DinnerItems { get; set; }
        public virtual DbSet<Lunch> Lunches { get; set; }
        public virtual DbSet<LunchItem> LunchItems { get; set; }
        public virtual DbSet<SnackItem> SnackItems { get; set; }
        public virtual DbSet<Snack> Snacks { get; set; }
    }
}
