//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyMealPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Snack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Snack()
        {
            this.DailyMeals = new ObservableListSource<DailyMeal>();
            this.DailyMeals1 = new ObservableListSource<DailyMeal>();
            this.DailyMeals2 = new ObservableListSource<DailyMeal>();
            this.DailyMeals3 = new ObservableListSource<DailyMeal>();
            this.DailyMeals4 = new ObservableListSource<DailyMeal>();
            this.DailyMeals5 = new ObservableListSource<DailyMeal>();
            this.DailyMeals6 = new ObservableListSource<DailyMeal>();
        }
    
        public long SnackID { get; set; }
        public Nullable<long> Calories { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<DailyMeal> DailyMeals6 { get; set; }
    }
}
